/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Evento;
import Models.Notificacao;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Portatilcar
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group = new javax.swing.ButtonGroup();
        DadosUtilizador = new javax.swing.JTabbedPane();
        EventosTab = new javax.swing.JPanel();
        eventosScroll = new javax.swing.JScrollPane();
        TableTexto = new javax.swing.JTable();
        CriarEventoButton = new javax.swing.JButton();
        criarApostaButton = new javax.swing.JButton();
        BemVindo = new javax.swing.JLabel();
        Utilizador = new javax.swing.JLabel();
        Coins = new javax.swing.JLabel();
        InfoEvento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        UtilizadorTab = new javax.swing.JPanel();
        Nome = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        NomeText = new javax.swing.JLabel();
        EmailText = new javax.swing.JLabel();
        Coins1 = new javax.swing.JLabel();
        CoinText = new javax.swing.JLabel();
        Deposito = new javax.swing.JRadioButton();
        Levantamento = new javax.swing.JRadioButton();
        ValorText = new javax.swing.JTextField();
        Valor = new javax.swing.JLabel();
        ValorButton = new javax.swing.JButton();
        ErroMessage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        NotificacaoTable = new javax.swing.JTable();
        BookieTab = new javax.swing.JPanel();
        Nome1 = new javax.swing.JLabel();
        NomeText1 = new javax.swing.JLabel();
        Email1 = new javax.swing.JLabel();
        EmailText1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableTexto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Evento", "Equipa1", "Odd Equipa1", "Odd Empate", "Equipa2", "Odd Equipa 2", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        eventosScroll.setViewportView(TableTexto);
        if (TableTexto.getColumnModel().getColumnCount() > 0) {
            TableTexto.getColumnModel().getColumn(0).setResizable(false);
        }

        CriarEventoButton.setText("CriarEvento");

        criarApostaButton.setText("Criar Aposta");

        BemVindo.setText("Bem Vindo:");

        Utilizador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Coins.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        InfoEvento.setText("Info Evento");

        jLabel1.setText("Coins");

        javax.swing.GroupLayout EventosTabLayout = new javax.swing.GroupLayout(EventosTab);
        EventosTab.setLayout(EventosTabLayout);
        EventosTabLayout.setHorizontalGroup(
            EventosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EventosTabLayout.createSequentialGroup()
                .addGroup(EventosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EventosTabLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(EventosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BemVindo)
                            .addGroup(EventosTabLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(EventosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CriarEventoButton)
                                    .addGroup(EventosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(criarApostaButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(InfoEvento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(EventosTabLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(EventosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Utilizador, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addGroup(EventosTabLayout.createSequentialGroup()
                                .addComponent(Coins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addGap(3, 3, 3)))))
                .addGap(29, 29, 29)
                .addComponent(eventosScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addContainerGap())
        );
        EventosTabLayout.setVerticalGroup(
            EventosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EventosTabLayout.createSequentialGroup()
                .addGroup(EventosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EventosTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(eventosScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EventosTabLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(BemVindo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Utilizador, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(EventosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EventosTabLayout.createSequentialGroup()
                                .addComponent(Coins, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(CriarEventoButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(criarApostaButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(InfoEvento))
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DadosUtilizador.addTab("Eventos", EventosTab);
        EventosTab.getAccessibleContext().setAccessibleName("Eventos");

        Nome.setText("Nome:");

        Email.setText("Email:");

        CoinText.setText("Coins:");

        group.add(Deposito);
        Deposito.setText("Deposito");
        Deposito.setActionCommand("deposito");

        group.add(Levantamento);
        Levantamento.setText("Levantamento");
        Levantamento.setActionCommand("levantamento");

        Valor.setText("Valor");

        ValorButton.setText("Fazer Transacção");

        jLabel2.setText("Notificações:");

        NotificacaoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Notificacao", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(NotificacaoTable);
        if (NotificacaoTable.getColumnModel().getColumnCount() > 0) {
            NotificacaoTable.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout UtilizadorTabLayout = new javax.swing.GroupLayout(UtilizadorTab);
        UtilizadorTab.setLayout(UtilizadorTabLayout);
        UtilizadorTabLayout.setHorizontalGroup(
            UtilizadorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UtilizadorTabLayout.createSequentialGroup()
                .addGroup(UtilizadorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UtilizadorTabLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(UtilizadorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UtilizadorTabLayout.createSequentialGroup()
                                .addGroup(UtilizadorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nome)
                                    .addComponent(Email)
                                    .addComponent(CoinText))
                                .addGap(18, 18, 18)
                                .addGroup(UtilizadorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Coins1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(UtilizadorTabLayout.createSequentialGroup()
                                .addComponent(Deposito)
                                .addGap(18, 18, 18)
                                .addComponent(Levantamento))
                            .addGroup(UtilizadorTabLayout.createSequentialGroup()
                                .addComponent(Valor)
                                .addGap(18, 18, 18)
                                .addComponent(ValorText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(UtilizadorTabLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(ValorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UtilizadorTabLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(ErroMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(UtilizadorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UtilizadorTabLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel2)
                        .addGap(223, 223, 223))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UtilizadorTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        UtilizadorTabLayout.setVerticalGroup(
            UtilizadorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UtilizadorTabLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(UtilizadorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UtilizadorTabLayout.createSequentialGroup()
                        .addGroup(UtilizadorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(UtilizadorTabLayout.createSequentialGroup()
                                .addGroup(UtilizadorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NomeText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nome))
                                .addGap(18, 18, 18)
                                .addComponent(Email))
                            .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(UtilizadorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CoinText, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Coins1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(UtilizadorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Deposito)
                            .addComponent(Levantamento))
                        .addGap(18, 18, 18)
                        .addGroup(UtilizadorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Valor)
                            .addComponent(ValorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(ValorButton)
                        .addGap(53, 53, 53)
                        .addComponent(ErroMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UtilizadorTabLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        DadosUtilizador.addTab("DadosApostador", UtilizadorTab);

        Nome1.setText("Nome:");

        Email1.setText("Email:");

        javax.swing.GroupLayout BookieTabLayout = new javax.swing.GroupLayout(BookieTab);
        BookieTab.setLayout(BookieTabLayout);
        BookieTabLayout.setHorizontalGroup(
            BookieTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookieTabLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(BookieTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nome1)
                    .addComponent(Email1))
                .addGap(18, 18, 18)
                .addGroup(BookieTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomeText1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailText1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(362, Short.MAX_VALUE))
        );
        BookieTabLayout.setVerticalGroup(
            BookieTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookieTabLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(BookieTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BookieTabLayout.createSequentialGroup()
                        .addGroup(BookieTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeText1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nome1))
                        .addGap(18, 18, 18)
                        .addComponent(Email1))
                    .addComponent(EmailText1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(398, Short.MAX_VALUE))
        );

        DadosUtilizador.addTab("DadosBookie", BookieTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DadosUtilizador)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DadosUtilizador, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );

        DadosUtilizador.getAccessibleContext().setAccessibleName("Eventos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }
    
    public void addCriarEventoListener(ActionListener listenForRegistoButton){
	        CriarEventoButton.addActionListener(listenForRegistoButton);	         
    }
    
    public void addTransacaoListener(ActionListener listenForTransacaoButton){
                ValorButton.addActionListener(listenForTransacaoButton);
    }
    
    public void addEventoInfoListener(ActionListener listenforEventoButton){
                InfoEvento.addActionListener(listenforEventoButton);
    }
    
    public void addCriarApostaListener(ActionListener listenForApostaButton){
                criarApostaButton.addActionListener(listenForApostaButton);
    }
    
    public void setUtilizadorText(String text){Utilizador.setText(text);}
    public void setEmailText(String text){EmailText.setText(text);}          
    public void setNomeText(String text){NomeText.setText(text);}
    public void setBetESS(double text){
        Coins.setText(String.valueOf(text));
        Coins1.setText(String.valueOf(text));
    }
    
    public int getEvento(){
       int selectedRowIndex = TableTexto.getSelectedRow();
       return selectedRowIndex;
    }
    
    public void setErro(String text){ ErroMessage.setText(text);}
    public String getValor(){return ValorText.getText();}
    public String getEscolha(){return group.getSelection().getActionCommand();}
    public void OffApostador(){ this.DadosUtilizador.remove(UtilizadorTab);}
    public void OnApostador(){ this.DadosUtilizador.add("Dados Apostador", UtilizadorTab);}
    public void OffBookie(){ this.DadosUtilizador.remove(BookieTab);}
    public void OnBookie(){ this.DadosUtilizador.add("Dados Bookie",BookieTab);}
    
    public void setTable(HashMap<Integer,Evento> eventos){
        
        DefaultTableModel model = (DefaultTableModel) TableTexto.getModel();
        model.setRowCount(0);
        for(Integer i: eventos.keySet()){ 
            float odd1 = eventos.get(i).getOdds().getOdd1();
            float oddx = eventos.get(i).getOdds().getOddx();          
            float odd2 = eventos.get(i).getOdds().getOdd2();          
            model.addRow(new String[]{String.valueOf(i),eventos.get(i).getEquipa1(),String.valueOf(odd1),String.valueOf(oddx),eventos.get(i).getEquipa2(),String.valueOf(odd2),String.valueOf(eventos.get(i).isOpen())});   
        }
        model.fireTableDataChanged();       
    }
    
    public void setTableNotif(ArrayList<Notificacao> notificacoes){
        DefaultTableModel model = (DefaultTableModel) NotificacaoTable.getModel();
        model.setRowCount(0);
        for(Notificacao a: notificacoes){
            String notific = a.getNotif();
            String data = ""+a.getDate();
            model.addRow(new String[]{notific,data});
        }
        model.fireTableDataChanged();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BemVindo;
    private javax.swing.JPanel BookieTab;
    private javax.swing.JLabel CoinText;
    private javax.swing.JLabel Coins;
    private javax.swing.JLabel Coins1;
    private javax.swing.JButton CriarEventoButton;
    private javax.swing.JTabbedPane DadosUtilizador;
    private javax.swing.JRadioButton Deposito;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Email1;
    private javax.swing.JLabel EmailText;
    private javax.swing.JLabel EmailText1;
    private javax.swing.JLabel ErroMessage;
    private javax.swing.JPanel EventosTab;
    private javax.swing.JButton InfoEvento;
    private javax.swing.JRadioButton Levantamento;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Nome1;
    private javax.swing.JLabel NomeText;
    private javax.swing.JLabel NomeText1;
    private javax.swing.JTable NotificacaoTable;
    private javax.swing.JTable TableTexto;
    private javax.swing.JLabel Utilizador;
    private javax.swing.JPanel UtilizadorTab;
    private javax.swing.JLabel Valor;
    private javax.swing.JButton ValorButton;
    private javax.swing.JTextField ValorText;
    private javax.swing.JButton criarApostaButton;
    private javax.swing.JScrollPane eventosScroll;
    private javax.swing.ButtonGroup group;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
